# Generated by Django 6.0.3 on 2026-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('delay', models.IntegerField()),
                ('on_time', models.IntegerField()),
            ],
        ),
    ]
