# Generated by Django 6.0.3 on 2026-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_relay_alter_gardening_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_on', models.BooleanField(default=False)),
                ('off_delay', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Relay',
        ),
        migrations.RemoveField(
            model_name='gardening',
            name='on_time',
        ),
    ]
