# Generated by Django 6.0.3 on 2026-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_manual_sensor_data_delete_relay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
